name: npm-build

# Only trigger on:
# - master branch
# - PR or Pull Request event types
# - Exclide Docusaurus files: this file, docs/** and website/**
on:
  push:
    branches:
      - master
      - release/**
    paths-ignore:
      - '.github/workflows/docusaurus.yml'
      - 'docs/**'
      - 'website/**'
  pull_request:
    branches:
      - master
      - release/*
    paths-ignore:
      - '.github/workflows/docusaurus.yml'
      - 'docs/**'
      - 'website/**'
jobs:
  package-build:
    name: Build on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

  package-release:
    if: ${{ github.event_name == 'push' }}
    needs: package-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://registry.npmjs.org/
          access: public
          dry-run: false
          check-version: true
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub
        uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com
          access: public
          dry-run: false
          check-version: true
          token: ${{ secrets.GITHUB_TOKEN }}